version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  # Altere para "5433:5432" se necessário
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: meu-backend  # Imagem pré-construída
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - CLIENT_URL=${CLIENT_URL}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    image: meu-frontend  # Imagem pré-construída
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
