version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      # Usuário administrativo do PostgreSQL. Guarde esta credencial em local seguro!
      POSTGRES_USER: "cursosflix_user"
      # Senha forte para o usuário. Guarde esta credencial em local seguro!
      POSTGRES_PASSWORD: "StrongP@ssw0rd_2025!"
      # Nome do banco de dados a ser criado
      POSTGRES_DB: "cursosflix"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cursosflix_user -d cursosflix"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
